name: Cypress Tests

on:
  push:
    branches:
      - isaac

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build --if-present

      - name: Start Server
        run: npm run start

      - name: Wait for Server to Start
        run: sleep 5s

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
        env:
          CYPRESS_CLOUDINARY_API_KEY: ${{ secrets.CYPRESS_CLOUDINARY_API_KEY }}
          CYPRESS_CLOUDINARY_API_SECRET: ${{ secrets.CYPRESS_CLOUDINARY_API_SECRET }}
          CYPRESS_CLOUDINARY_NAME: ${{ secrets.CYPRESS_CLOUDINARY_NAME }}
          CYPRESS_DB_CONNECTION_LIMIT: ${{ secrets.CYPRESS_DB_CONNECTION_LIMIT }}
          CYPRESS_DB_DATABASE: ${{ secrets.CYPRESS_DB_DATABASE }}
          CYPRESS_DB_HOST: ${{ secrets.CYPRESS_DB_HOST }}
          CYPRESS_DB_PASSWORD: ${{ secrets.CYPRESS_DB_PASSWORD }}
          CYPRESS_DB_USER: ${{ secrets.CYPRESS_DB_USER }}
          CYPRESS_ELASTICAPIKEY: ${{ secrets.CYPRESS_ELASTICAPIKEY }}
          CYPRESS_ELASTICEMAIL: ${{ secrets.CYPRESS_ELASTICEMAIL }}
          CYPRESS_ENCRYPTIV: ${{ secrets.CYPRESS_ENCRYPTIV }}
          CYPRESS_ENCRYPTKEY: ${{ secrets.CYPRESS_ENCRYPTKEY }}
          CYPRESS_PORT: ${{ secrets.CYPRESS_PORT }}
          CYPRESS_SECRETKEY: ${{ secrets.CYPRESS_SECRETKEY }}
          CYPRESS_TWILIONUMBER: ${{ secrets.CYPRESS_TWILIONUMBER }}
          CYPRESS_TWILIOSID: ${{ secrets.CYPRESS_TWILIOSID }}
          CYPRESS_TWILIOTOKEN: ${{ secrets.CYPRESS_TWILIOTOKEN }}
