name: Cypress Tests

on:
  push:
    branches:
      - isaac

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build --if-present

      - name: Start Server
        run: npm run start

      - name: Wait for Server to Start
        run: sleep 1s

      - name: Set up Environment Variables
        run: |
          echo "CYPRESS_API_KEY=${{ secrets.CYPRESS_API_KEY }}" >> $GITHUB_ENV
          echo "CYPRESS_USERNAME=${{ secrets.CYPRESS_USERNAME }}" >> $GITHUB_ENV
          echo "CYPRESS_cloudinary_api_secret: ${{ secrets.CYPRESS_CLOUDINARY_API_KEY }}" >> $GITHUB_ENV
          echo "CYPRESS_cloudinary_api_key: ${{ secrets.CYPRESS_CLOUDINARY_API_SECRET }}" >> $GITHUB_ENV
          echo "CYPRESS_cloudinary_name: ${{ secrets.CYPRESS_CLOUDINARY_NAME }}" >> $GITHUB_ENV
          echo "CYPRESS_DB_CONNECTION_LIMIT: ${{ secrets.CYPRESS_DB_CONNECTION_LIMIT }}" >> $GITHUB_ENV
          echo "CYPRESS_DB_DATABASE: ${{ secrets.CYPRESS_DB_DATABASE }}" >> $GITHUB_ENV
          echo "CYPRESS_DB_HOST: ${{ secrets.CYPRESS_DB_HOST }}" >> $GITHUB_ENV
          echo "CYPRESS_DB_PASSWORD: ${{ secrets.CYPRESS_DB_PASSWORD }}" >> $GITHUB_ENV
          echo "CYPRESS_DB_USER: ${{ secrets.CYPRESS_DB_USER }}" >> $GITHUB_ENV
          echo "CYPRESS_elasticAPIKey: ${{ secrets.CYPRESS_ELASTICAPIKEY }}" >> $GITHUB_ENV
          echo "CYPRESS_elasticEmail: ${{ secrets.CYPRESS_ELASTICEMAIL }}" >> $GITHUB_ENV
          echo "CYPRESS_encryptIV: ${{ secrets.CYPRESS_ENCRYPTIV }}" >> $GITHUB_ENV
          echo "CYPRESS_encryptKey: ${{ secrets.CYPRESS_ENCRYPTKEY }}" >> $GITHUB_ENV
          echo "CYPRESS_PORT: ${{ secrets.CYPRESS_PORT }}" >> $GITHUB_ENV
          echo "CYPRESS_SECRETKEY: ${{ secrets.CYPRESS_SECRETKEY }}" >> $GITHUB_ENV
          echo "CYPRESS_twilioNumber: ${{ secrets.CYPRESS_TWILIONUMBER }}" >> $GITHUB_ENV
          echo "CYPRESS_twilioSID: ${{ secrets.CYPRESS_TWILIOSID }}" >> $GITHUB_ENV
          echo "CYPRESS_twilioToken: ${{ secrets.CYPRESS_TWILIOTOKEN }}" >> $GITHUB_ENV

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
