name: Cypress Tests

on:
  push:
    branches:
      - isaac

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3
          
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"
        env:
            CYPRESS_cloudinary_api_secret: ${{ secrets.CYPRESS_CLOUDINARY_API_KEY }}
            CYPRESS_cloudinary_api_key: ${{ secrets.CYPRESS_CLOUDINARY_API_SECRET }}
            CYPRESS_cloudinary_name: ${{ secrets.CYPRESS_CLOUDINARY_NAME }}
            CYPRESS_DB_CONNECTION_LIMIT: ${{ secrets.CYPRESS_DB_CONNECTION_LIMIT }}
            CYPRESS_DB_DATABASE: ${{ secrets.CYPRESS_DB_DATABASE }}
            CYPRESS_DB_HOST: ${{ secrets.CYPRESS_DB_HOST }}
            CYPRESS_DB_PASSWORD: ${{ secrets.CYPRESS_DB_PASSWORD }}
            CYPRESS_DB_USER: ${{ secrets.CYPRESS_DB_USER }}
            CYPRESS_elasticAPIKey: ${{ secrets.CYPRESS_ELASTICAPIKEY }}
            CYPRESS_elasticEmail: ${{ secrets.CYPRESS_ELASTICEMAIL }}
            CYPRESS_encryptIV: ${{ secrets.CYPRESS_ENCRYPTIV }}
            CYPRESS_encryptKey: ${{ secrets.CYPRESS_ENCRYPTKEY }}
            CYPRESS_PORT: ${{ secrets.CYPRESS_PORT }}
            CYPRESS_SECRETKEY: ${{ secrets.CYPRESS_SECRETKEY }}
            CYPRESS_twilioNumber: ${{ secrets.CYPRESS_TWILIONUMBER }}
            CYPRESS_twilioSID: ${{ secrets.CYPRESS_TWILIOSID }}
            CYPRESS_twilioToken: ${{ secrets.CYPRESS_TWILIOTOKEN }}
        
