name: Cypress Tests

on:
  push:
    branches:
      - isaac

jobs:
  Cypress-Test:
    runs-on: windows-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3
          
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          start: npm start
        env:
            cloudinary_api_secret: ${{ secrets.CYPRESS_CLOUDINARY_API_KEY }}
            cloudinary_api_key: ${{ secrets.CYPRESS_CLOUDINARY_API_SECRET }}
            cloudinary_name: ${{ secrets.CYPRESS_CLOUDINARY_NAME }}
            DB_CONNECTION_LIMIT: ${{ secrets.CYPRESS_DB_CONNECTION_LIMIT }}
            DB_DATABASE: ${{ secrets.CYPRESS_DB_DATABASE }}
            DB_HOST: ${{ secrets.CYPRESS_DB_HOST }}
            DB_PASSWORD: ${{ secrets.CYPRESS_DB_PASSWORD }}
            DB_USER: ${{ secrets.CYPRESS_DB_USER }}
            elasticAPIKey: ${{ secrets.CYPRESS_ELASTICAPIKEY }}
            elasticEmail: ${{ secrets.CYPRESS_ELASTICEMAIL }}
            encryptIV: ${{ secrets.CYPRESS_ENCRYPTIV }}
            encryptKey: ${{ secrets.CYPRESS_ENCRYPTKEY }}
            PORT: ${{ secrets.CYPRESS_PORT }}
            SECRETKEY: ${{ secrets.CYPRESS_SECRETKEY }}
            twilioNumber: ${{ secrets.CYPRESS_TWILIONUMBER }}
            twilioSID: ${{ secrets.CYPRESS_TWILIOSID }}
            twilioToken: ${{ secrets.CYPRESS_TWILIOTOKEN }}
        
